apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.cronjob.name }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Values.cronjob.name }}
            image: {{ .Values.cronjob.image }}
            args: {{ toYaml .Values.cronjob.args | indent 12 }}
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
