apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    secret.reloader.stakater.com/reload: secret-name
  labels: {{- include "fpost-app.labels" . | nindent 4 }}
  name: {{ include "fpost-app.fullname" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels: {{- include "fpost-app.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels: {{- include "fpost-app.labels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      containers:
      - env:
        - name: ENV_NAME
          value: {{ .Values.config.ENV_NAME }}
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                key: db_url
                name: fpost-app-db-secret
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: fpost-app-db-secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: fpost-app-db-secret
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 1
          failureThreshold: 2
        name: {{ include "fpost-app.fullname" . }}
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources: {{- toYaml .Values.resources | nindent 10 }}
      imagePullSecrets:
      - name: {{ .Values.Environment }}-secret
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumeMounts:
      - mountPath: /data
        name: {{ include "fpost-app.fullname" . }}
    imagePullSecrets:
    - name: {{ .Values.Environment }}-secret
    volumes:
    - name: {{ include "fpost-app.fullname" . }}
      persistentVolumeClaim:
        claimName: pvc-{{ include "fpost-app.fullname" . }}
