apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "fpost-app.fullname" . }}-secret
spec:
  refreshInterval: 3m
  secretStoreRef:
    name: {{ .Values.VAULT_SECRET_BACKEND }}
    kind: ClusterSecretStore
  target:
    name: fpost-app-db-secret
    template:
      metadata:
        annotations:
          reloader.stakater.com/match: "true"
  data:
{{- range slice "db_url" "username" "password" }}
  - secretKey: {{ . }}
    remoteRef:
      key: {{ .Values.config.ENV_NAME }}/fpost-app-db-secret
      property: {{ . }}
{{- end }}
