apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  labels: {{- include "fpost-app.labels" . | nindent 4 }}
  name: {{ include "fpost-app.fullname" . }}
spec:
  rules:
  - host: {{ include "fpost-app.fullname" . }}.fpost.com
    http:
      paths:
      - backend:
          service:
            name: {{ include "fpost-app.fullname" . }}
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ include "fpost-app.fullname" . }}.fpost.com
    secretName: wildcard-certificate.letsencrypt
