apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "fpost-app.fullname" . }}-pdb
  labels: {{ include "fpost-app.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels: {{ include "fpost-app.selectorLabels" . | nindent 6 }}
