apiVersion: v1
kind: Service
metadata:
  labels: {{- include "fpost-app.labels" . | nindent 4 }}
  name: {{ include "fpost-app.fullname" . }}
spec:
  ports:
  - name: fpost-app-port
    port: 80
  selector: {{- include "fpost-app.selectorLabels" . | nindent 6 }}
  type: ClusterIP
  