Environment: production
branch: main
image:
  name: strm/helloworld
  tag: latest
config:
  ENV_NAME: production
  DB_VPC_CIDR: "10.0.1.0/20"

maxReplicas: 10
resources:
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "0.5"
    memory: "0.5Gi"

# Cronjob configuration

cronjob:
  name: hello-world-cronjob
  schedule: "*/30 * * * *"
  image: busybox
  args:
    - /bin/sh
    - -c
    - echo "Hello World"
  restartPolicy: OnFailure
